### PR TITLE
French translation update

### PR DESCRIPTION
**Pull request by trebmuh**

### CODE REVIEW

**Comment by trebmuh** [comment]
@liushuyu : here is an update for the French translation of the website

**Comment by liushuyu** [comment]
Thanks!

**Comment by trebmuh** [comment]
And thanks to you for the quick merge @liushuyu .
Don't hesitate to ping me when it seems that I missed an update (like it was there).
Have a nice day.

**Comment by liushuyu** [comment]
>And thanks to you for the quick merge @liushuyu .

You are welcome!

>Don't hesitate to ping me when it seems that I missed an update (like it was there).
Have a nice day.

Sure. But since the updates are done manually, so I wouldn't immediately know if the source files are updated in the upstream repository. I am considering writing a script to automate this process. Also, translations coming from the Transifex platform always wipe your name from the list for some reasons, so I am making a standalone contributor list to record all the names of the translators to address this issue. I apologize for that.

Thanks again!

**Comment by trebmuh** [comment]
OK, I was wondering why, and now, I know!

**Comment by trebmuh** [comment]
@liushuyu I've just checked, and it seems that the website hasn't been updated with those translations i made here. Since I don't know if that is to be expected or not, I'm mentioning it here.

By the way, I'll not be available in July and will be back to my computer in August, so if there are new translations to be made, I'll do those then.

**Comment by trebmuh** [comment]
@liushuyu ping?

**Pull request merged**
