### PR TITLE
Update fr.ts

### PR DESCRIPTION
**Pull request by trebmuh**
Update FR translation.

### CODE REVIEW

**Comment by liushuyu** [comment]
Sorry but XML structure problems also exist this time...

```
XMLSyntaxError: Opening and ending tag mismatch: message line 6490 and translation, line 6492, column 56
```

**NOTE**: Maybe there are multiple problems, but to prevent from false-positive, only the first one is reported

**Comment by trebmuh** [comment]
@liushuyu : yes, you were right. I fixed it. Let me know if you find any other issue.

**Comment by liushuyu** [comment]
Thanks

**Comment by trebmuh** [comment]
sweet

**Pull request merged**
